"use client";

import React, { useEffect, useRef } from "react";
import { useInView } from "framer-motion";
import type { TemplatePreviewProps } from "./previews/types";
import { StarryConstellationPreview } from "./valentine-1/preview";
import { Valentine2Preview } from "./valentine-2/preview";
import { Valentine3Preview } from "./valentine-3/preview";
import { WillYouDateMePreview } from "./dating-1/preview";
import { BirthdayMagicPreview } from "./birthday-1/preview";
import { DatingTwoPreview } from "./dating-2/preview";
import { DatingThreePreview } from "./dating-3/preview";
import Birthday2Preview from "./birthday-2/preview";

type InteractiveTemplatePreviewProps = TemplatePreviewProps & {
  componentKey: string;
  roomId?: string;
};

const previewRegistry = [
  { match: "val-starry-constellation", Component: StarryConstellationPreview },
  { match: "constellation", Component: StarryConstellationPreview },
  { match: "starry", Component: StarryConstellationPreview },
  { match: "valentine-1", Component: StarryConstellationPreview },
  { match: "valentine #1", Component: StarryConstellationPreview },
  { match: "valentine-2", Component: Valentine2Preview },
  { match: "valentine #2", Component: Valentine2Preview },
  { match: "valentine-3", Component: Valentine3Preview },
  { match: "valentine #3", Component: Valentine3Preview },
  { match: "will-you-date-me", Component: WillYouDateMePreview },
  { match: "dating-1", Component: WillYouDateMePreview },
  { match: "dating #1", Component: WillYouDateMePreview },
  { match: "dating-2", Component: DatingTwoPreview },
  { match: "dating #2", Component: DatingTwoPreview },
  { match: "dating-3", Component: DatingThreePreview },
  { match: "dating #3", Component: DatingThreePreview },
  { match: "birthday-magic", Component: BirthdayMagicPreview },
  { match: "birthday-1", Component: BirthdayMagicPreview },
  { match: "birthday #1", Component: BirthdayMagicPreview },
  { match: "birthday-2", Component: Birthday2Preview },
  { match: "birthday #2", Component: Birthday2Preview },
];

// This bot automatically plays through ANY template by clicking buttons intelligently
function BotAutoPlayer({ children, enabled }: { children: React.ReactNode; enabled: boolean }) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!enabled) return;

    let isActive = true;
    const interval = setInterval(() => {
      if (!isActive || !containerRef.current) return;
      
      const buttons = Array.from(containerRef.current.querySelectorAll('button'));
      const clickableTexts = ["CÓ", "YES", "Tiếp tục", "Chọn", "Mở", "Xem Tiếp", "Lên đồ", "Hoàn thành", "Bắt đầu", "Click", "Tiếp", "Next"];
      
      let clicked = false;
      
      // 1. Try to find a primary 'next' or 'yes' button
      for (const btn of buttons) {
        const text = btn.textContent || "";
        if (clickableTexts.some(t => text.toLowerCase().includes(t.toLowerCase()))) {
           if (btn.disabled) continue;
           btn.click();
           clicked = true;
           break;
        }
      }
      
      // 2. If no clear 'next' button, just click a random option (useful for selecting food/movie/etc)
      if (!clicked && buttons.length > 0) {
        const enabledButtons = buttons.filter(b => !b.disabled);
        if (enabledButtons.length > 0) {
          const randomBtn = enabledButtons[Math.floor(Math.random() * enabledButtons.length)];
          randomBtn.click();
        }
      }
      
    }, 2500);

    return () => {
      isActive = false;
      clearInterval(interval);
    };
  }, [enabled]);

  const handleContainerClick = (e: React.MouseEvent) => {
    // If this click was generated by our script (BotAutoPlayer), stop it from bubbling up to the <Link> parent
    if (!e.nativeEvent.isTrusted) {
      e.preventDefault();
      e.stopPropagation();
    }
  };

  return <div ref={containerRef} className="w-full h-full relative" onClick={handleContainerClick}>{children}</div>;
}

export function InteractiveTemplatePreview({
  componentKey,
  roomId,
  ...props
}: InteractiveTemplatePreviewProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const isInView = useInView(containerRef, { amount: 0.1 });
  const normalizedKey = componentKey.toLowerCase();
  const preview = previewRegistry.find((item) => normalizedKey.includes(item.match));

  if (preview) {
    const Component = preview.Component;
    if (props.compact) {
      if (!props.isBuilderPreview) {
        return (
          <div ref={containerRef} className="mx-auto flex aspect-[9/19] w-[340px] max-w-full shrink-0 flex-col overflow-hidden rounded-[2.5rem] border-[6px] border-[#150a21] bg-[#05020a] shadow-2xl relative pointer-events-none">
            <BotAutoPlayer enabled={isInView}>
              <Component {...props} roomId={roomId} autoPlay={isInView} />
            </BotAutoPlayer>
          </div>
        );
      } else {
        return (
          <div ref={containerRef} className="mx-auto flex aspect-[9/19] w-[340px] max-w-full shrink-0 flex-col overflow-hidden rounded-[2.5rem] border-[6px] border-[#150a21] bg-[#05020a] shadow-2xl relative">
            <Component {...props} roomId={roomId} autoPlay={isInView} />
          </div>
        );
      }
    }
    return <Component {...props} roomId={roomId} />;
  }

  return <FallbackPreview componentKey={componentKey} {...props} />;
}

function FallbackPreview({
  visualLabel,
  recipientName = "Linh",
  compact = false,
}: TemplatePreviewProps & { componentKey: string }) {
  return (
    <div className="relative grid h-full min-h-56 place-items-center overflow-hidden rounded-2xl border border-white/12 bg-[#12091f] p-5 text-center text-white">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_18%,rgba(255,79,216,0.32),transparent_32%),linear-gradient(145deg,rgba(155,92,255,0.28),transparent)]" />
      <div className="relative">
        <div className="float-slow mx-auto grid h-20 w-20 place-items-center rounded-full border border-white/20 bg-white/12 text-xs font-black shadow-[0_0_36px_rgba(255,79,216,0.28)]">
          {visualLabel || "LOVE"}
        </div>
        <h3 className={compact ? "mt-4 text-2xl font-bold" : "mt-5 text-4xl font-bold"}>
          Quà tặng cho {recipientName}
        </h3>
        <p className="mx-auto mt-3 max-w-xs text-xs leading-5 text-white/64">
          Template này đang chờ visual riêng. Admin có thể thêm preview component theo component_key.
        </p>
      </div>
    </div>
  );
}
